export const slideData = [
  [
    {
      title: "아우트로 커피산성",
      text: "청주 근교 커피가 맛있는 남성 아우트로 카페로 버섯 모양의 독특한 지붕이 손님의 시선을 화로 잡는다. 회색벽돌과 회색 지붕의 단일 컬러로 마치 이 건물이 자연에서 발견할 수 있는 아름다운 곡선의 돌 조각상으로 보여진다. 아우트로 커피는 다양한 디저트 빵이 준비되어 있다. 빵은 직접 반죽, 당일 생산, 당일 폐기를 원칙으로 한다. ",
      images: [
        "아우트로1.jpeg",
        "아우트로2.jpeg",
        "아우트로3.jpeg",
        "아우트로4.jpeg",
        "아우트로5.jpeg",
      ],
      sns: "@outro_coffee",
      hash: "#Natrue #Photo Zone #Cafe",
      contentId: "2766501",
      sigun: "충북 청주시 가경읍",
      contentType: "39",
      link: "https://map.naver.com/p/entry/place/1204448436?placePath=%252Fhome%253Fentry%253Dplt&searchType=place&lng=127.5466516&lat=36.6509531",
    },
    {
      title: "모이핀",
      text: "모이핀은 여수 핫플레이스 오션뷰 카페다. 오션점, 스카이점 두 곳이 있으며 건물의 전고가 높아 확 트인 개방감을 주면서 통유리에 보여지는 여수의 바다 풍경은 일품이다. 각 층마다 다른 테마의 가구와 배치로 새로운 느낌을 준다.",
      images: [
        "모이핀1.jpeg",
        "모이핀2.jpeg",
        "모이핀3.jpeg",
        "모이핀4.jpeg",
        "모이핀5.jpeg",
      ],
      sns: "@cafe_moifin",
      hash: "#Shop# Café",
      contentId: "2931286",
      sigun: "전남 여수시 돌산읍",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EB%AA%A8%EC%9D%B4%ED%95%80/place/1879937186?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dpll",
    },
    {
      title: "묵리459",
      text: "묵리 459는 용인을 대표하는 자연 속의 브런치 & 로스터리 카페다. 먹을 만들던 마을에서 유래된 이름 묵리, 그 이름 그대로 묵리459로 옛 선조들의 '섬김' 정신을 바탕으로 고객님들을 맞이한다. 묵리 459의 건축 디자인은 계절을 담은 창, 자연 그대로의 날 것을 보여주기 위해 내부를 비우고 시선을 외부로 자연스럽게 유도한다. 봄. 여름, 가을, 겨울 사계절마다 다른 색을 입은 자연을 바라보며 저마다 느끼는 다양한 감정을 통해 힐링하는 시간이 될 수 있다.",
      images: [
        "묵리1.jpeg",
        "묵리2.jpeg",
        "묵리3.jpeg",
        "묵리4.jpeg",
        "묵리5.jpeg",
      ],
      sns: "@mukri459_official",
      hash: "#Natrue #Photo Zone #Cafe",
      contentId: "2837499",
      sigun: "경기 용인시 처인구",
      contentType: "39",
      link: "https://map.naver.com/p/entry/place/1496018206?lng=127.2384417&lat=37.1691205&placePath=%2Fhome&entry=plt&searchType=place&c=15.00,0,0,0,dh",
    },
    {
      title: "목새",
      text: "제주시 동쪽에 위치한 차분한 삼양 검은 모래해변에서 스스로와 마주하는 조용한 시간을 위한, 고요하고 오롯한 나의 요새 컨셉을 가진 카페다. '고요새'에서 알 수 있듯, 공간을 함께 나누는 타인을 배려하여 대화는 소곤하게 하는 것이 특징이다. 원래 이름은 '고요새'였으나 현재 '목새'로 바뀌었다.",
      images: [
        "고요새1.jpeg",
        "고요새2.jpeg",
        "고요새3.jpeg",
        "고요새4.jpeg",
        "고요새5.jpeg",
      ],
      sns: "@goyosae__",
      hash: "#Cafe",
      contentId: "2853453",
      sigun: "제주도 제주시",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EB%AA%A9%EC%83%88/place/1456230383?placePath=?entry=pll&from=nx&fromNxList=true&searchType=place",
    },
    {
      title: "소노펠리체 델피노 더 엠브로시아",
      text: "고성의 소노 펠리체 델 피노 10층에 위치한 앰브로시아 카페는 세계적으로 유명한 설악산의 울산바위 전망을 즐길 수 있는 공간이다. 계절마다 다른 설악의 풍경과 함께 향긋한 커피와 당일 갓 구운 베이커리를 자연과 함께하는 아름다운 풍경 속에서 즐길 수 있다.",
      images: [
        "소노펠리체1.jpeg",
        "소노펠리체2.jpeg",
        "소노펠리체3.jpeg",
        "소노펠리체4.jpeg",
        "소노펠리체5.jpeg",
      ],
      sns: "",
      hash: "#Cafe",
      contentId: "2818350",
      sigun: "강원 고성군 토성면",
      contentType: "39",
      link: "https://map.naver.com/p/entry/place/1738635586?placePath=%252Fhome%253Fentry%253Dplt&searchType=place&lng=128.4968821&lat=38.2092721&c=15.00,0,0,0,dh",
    },
    {
      title: "팔숲",
      text: "팔숲은 산밑 조용하고 한적한 곳에 위치해 있는 브런치 맛집, 나무들로 가득한 숲속 에서 여러분들의 지친 일상에 힐링을 전해주는 향기로운 카페다. 특히 카페 2층은 전체적인 통창으로 되어 있어서 팔숲 특유의 통창뷰 감성을 느끼기에 최적의 환경으로 이루어져 있다. 애견 동반도 가능하기 때문에 야외 테이블에서 여유로움을 느끼면서 포레스트 감성 느끼기도 좋고 같이 온 반려동물과 행복한 시간을 보내기에도 좋다.",
      images: [
        "팔숲1.jpeg",
        "팔숲2.jpeg",
        "팔숲3.jpeg",
        "팔숲4.jpeg",
        "팔숲5.jpeg",
      ],
      sns: "@palsoop_",
      hash: "#Natrue #Cafe",
      contentId: "2867787",
      sigun: "경기 남양주시 와부읍",
      contentType: "39",
      link: "https://map.naver.com/p/search/%ED%8C%94%EC%88%B2/place/1847807375?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "인크커피 가산점",
      text: "도심 속 여유를 즐겨볼 수 있는 카페다. 카페 안에는 큰 로스터리가 있고, 바닥부터 천장까지 유리창으로 둘러싸인 거대한 원형의 중庭이 인상적이다. 건물은 크고 지하실과 4층에 옥상 공간이 있다. 인근에는 여러 회사들이 있어 점심시간에는 사무직원으로 붐빈다.",
      images: [
        "인크커피1.jpeg",
        "인크커피2.jpeg",
        "인크커피3.jpeg",
        "인크커피4.jpeg",
        "인크커피5.jpeg",
      ],
      sns: "@inccoffee__",
      hash: "#Cafe",
      contentId: "2836657",
      sigun: "서울 금천구",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%9D%B8%ED%81%AC%EC%BB%A4%ED%94%BC%20%EA%B0%80%EC%82%B0%EC%A0%90/place/1232726331?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "카페 긷",
      text: "노학동의 '학'은 새인 '학'을 의미한다. 카페의 이름인 긷은 한국어로 새의 깃털을 의미하는 '깃'에서 유래했다. 낮은 들판을 건너고 올려다보면 거대한 산세가 펼쳐지며, 바위산이 웅장하게 솟아있는 풍경이 펼쳐진다. 편안하고 아름다운 디자인의 건물과 조화롭게 펼쳐진 풍경은 휴식을 취할 수 있는 멋진 장소다.",
      images: ["긷1.jpeg", "긷2.jpeg", "긷3.jpeg", "긷4.jpeg", "긷5.jpeg"],
      sns: "@sokcho.gid",
      hash: "#Cafe",
      contentId: "2913408",
      sigun: "강원 속초시 노학동",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%B9%B4%ED%8E%98%20%EA%B8%B7/place/1140350156?c=15.00,0,0,0,dh&placePath=%2Fphoto%3Fentry%253Dbmp",
    },
    {
      title: "공간태리",
      text: "공간 태리는 주변의 숲과 어우러진 도심 속의 자연공간으로 독특한 디자인을 가진 공간태리는 아치형 곡선이 바닥으로 이어져 두개의 건물이 마치 하나의 건물처럼 보인다.",
      images: [
        "공간태리1.jpeg",
        "공간태리2.jpeg",
        "공간태리3.jpeg",
        "공간태리4.jpeg",
        "공간태리5.jpeg",
      ],
      sns: "@o.ganteri.official",
      hash: "#Shop #Cafe",
      contentId: "2900942",
      sigun: "대전 유성구",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EA%B3%B5%EA%B0%84%ED%83%9C%EB%A6%AC/place/1457499042?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "논스페이스",
      text: "논스페이스 건물은 쌀알을 베고 난 논에 남아있는 쌀벼의 형태를 상징하고 있다. 건물은 세련되고 스타일리시한 분위기를 풍기고 있다. 노출된 콘크리트, 긴 커피 바, 그리고 나무 가구는 조화를 이루어 특별한 가치를 더해주며, 공간을 더욱 돋보이게 한다.",
      images: [
        "논스페이스1.jpeg",
        "논스페이스2.jpeg",
        "논스페이스3.jpeg",
        "논스페이스4.jpeg",
        "논스페이스5.jpeg",
      ],
      sns: "@nonspace_2000",
      hash: "#Cafe",
      contentId: "2847961",
      sigun: "경기 이천시 호법면",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EB%85%BC%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4/place/1610694749?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "무지개펜션에스프레소",
      text: "거제도의 최남단에 위치해 있는 조용하고 한적한 홍포마을의 카페, '무지개펜션에스프레소'이다. 거제도 관광지도에, 전망대로 네이버지도에 표시될 만큼 아름다운 '여차홍포해안비경'이 한눈에 들어오는 '무지개펜션'을 리뉴얼하여 카페로 운영하고 있다. 푸른 다도해의 아름다운 비경과 함께 즐기는 커피 한 잔의 여유, 바쁜일상에서 벗어나 여유롭게 바다와 음악을 감상하는 공간이기에 노키즈존으로 운영한다.",
      images: [
        "무지개1.jpeg",
        "무지개2.jpeg",
        "무지개3.jpeg",
        "무지개4.jpeg",
        "무지개5.jpeg",
      ],
      sns: "@mujigaepension",
      hash: "#Photo Zone #Cafe",
      contentId: "3060359",
      sigun: "경기 이천시 호법면",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EB%AC%B4%EC%A7%80%EA%B0%9C%ED%8E%9C%EC%85%98%EC%97%90%EC%8A%A4%ED%94%84%EB%A0%88%EC%86%8C/place/1591134521?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "꼬스뗀뇨",
      text: "코스테뇨(Costeño)는 제주의 구좌읍에 오픈한 카페로 구좌 해안도로를 따라 운전하는 도중 볼 수 있다. 제주 분위기 가득한 야외 정원의 야자수나무들이 여러분을 환영할 것이다. 노출된 콘크리트 벽이 특징인 인테리어는 숯색으로 가득 차 있다. 카페는 본관과 갤러리용 두 건물을 사한다. 내부는 바 테이블과 창가 테이블을 공유하는 넓은 공간으로, 음료를 즐기기 위한 갤러리 좌석도 찾을 수 있다. 이 카페는 커피를 즐기고 책을 읽거나 노트북으로 작업할 장소를 찾는 이들에게 좋은 선택지다.",
      images: [
        "꼬스뗀뇨1.jpeg",
        "꼬스뗀뇨2.jpeg",
        "꼬스뗀뇨3.jpeg",
        "꼬스뗀뇨4.jpeg",
        "꼬스뗀뇨5.jpeg",
      ],
      sns: "@_costeno",
      hash: "#Cafe #Dessert/Bakery",
      contentId: "2877801",
      sigun: "제주 제주시 구좌읍",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EA%BC%AC%EC%8A%A4%EB%97%80%EB%87%A8/place/1928288067?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "스위밍터틀",
      text: "스위밍터틀은 강원도 고성의 아야진 해변에 위치한 아름다운 파노라마 오션뷰 카페다. 동해 바다의 일출, 해질녘의 분홍 노을이 함께 어우러지는 풍경을 모든 좌석에서 편안하게 보실 수 있으며, 바다를 배경으로 한 바다정원에서 바라보는 노을도 매력적이다. 미술관과 같은 복도를 지나 푸른 바다를 마주하면 시간이 멈춘 것 같은 착각이 들기도 한다. 루프탑을 비롯하여 세련되고 깔끔한 인테리어로 편안한 분위기에서 평화로운 아야진 해변을 바라보며 편안한 휴식과 감성 충전을 할 수 있다.",
      images: [
        "스위밍터틀1.jpeg",
        "스위밍터틀2.jpeg",
        "스위밍터틀3.jpeg",
        "스위밍터틀4.jpeg",
        "스위밍터틀5.jpeg",
      ],
      sns: "@swimming.turtle.cafe",
      hash: "#Cafe",
      contentId: "2837878",
      sigun: "강원군 고성군 토성면",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%8A%A4%EC%9C%84%EB%B0%8D%ED%84%B0%ED%8B%80/place/1332280493?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "에이프레임",
      text: "에이프레임(A∙Frame)은 관광 명소 수준의 시네마틱 한적한 바다 경관과 서핑 보드로 장식된 인상적인 벽 장식을 볼 수 있다. 내부 공간은 외부에서 예상한 것보다 크며, 다양한 유형의 좌석이 방문객들이 억제 없는 바다 경관을 즐길 수 있다. 카페가 해변 클럽의 분위기를 건물 안으로 적절하게 가져와 방문객이 실제 여행을 갔다온 듯한 느낌을 받을 수 있도록 한 것이 인상적이다.",
      images: [
        "에이프레임1.jpeg",
        "에이프레임2.jpeg",
        "에이프레임3.jpeg",
        "에이프레임4.jpeg",
        "에이프레임5.jpeg",
      ],
      sns: "@aframe_cafe",
      hash: "#Photo Zone #Cafe",
      contentId: "2807083",
      sigun: "강원 고성 죽왕면",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%97%90%EC%9D%B4%ED%94%84%EB%A0%88%EC%9E%84/place/1721212179?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "케이프라운지",
      text: "포항의 호미곶에 위치한 이 풀 빌라와 카페는 Cape Lounge로 불린다. Cape Lounge는 초목 위의 휴식 라운지를 의미하는데 이곳에서 일출과 일몰을 감상할 수 있다. 또한 개방된 공간에서는 맑은 바다와 수영장의 광활한 전망을 즐길 수 있다.",
      images: [
        "케이프라운지1.jpeg",
        "케이프라운지2.jpeg",
        "케이프라운지3.jpeg",
        "케이프라운지4.jpeg",
        "케이프라운지5.jpeg",
      ],
      sns: "@capelounge_official",
      hash: "#Photo Zone #Cafe",
      contentId: "2842615",
      sigun: "경북 포항시 남구",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%BC%80%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9A%B4%EC%A7%80/place/1964978538?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "오른",
      text: "orrrn은 성산에 위치한 이 바다 전망 카페다. 외관은 탁월한 건축 미학을 보여줍니다. 노출된 콘크리트의 단순함이 깊은 푸른 제주 바다와 잘 어울린다. 물이 건물 주변을 흐르고, 풀은 바람에 흔들리며, 봄에는 유채꽃, 여름에는 해바라기, 가을에는 아름다운 억새가 무성히 피는 꽃으로 가득하다. 유리벽을 통해 카페의 모든 코너에서 광활한 바다 전망을 즐길 수 있으며, 야외 테라스와 옥상에 앉아있는 좌석은 성산 지역에서 이 카페를 특별하게 만든다.",
      images: [
        "오른1.jpeg",
        "오른2.jpeg",
        "오른3.jpeg",
        "오른4.jpeg",
        "오른5.jpeg",
      ],
      sns: "@orrrn_official",
      hash: "#Cafe",
      contentId: "2845353",
      sigun: "부산 사상구",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%98%A4%EB%A5%B8/place/1470713685?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "코랄라니",
      text: "코랄라니는 부산 기장에 위치한 새로 오픈한 대형 오션 뷰 카페다. 지하 1층부터 옥상까지 총 4층의 실내 층과 옥상 공간이 있습니다. 각 층마다 있는 야외 테라스는 오션 뷰를 즐기기에 최적의 장소다. 실내 공간은 불필요한 장식 없이 간결하고 현대적으로 제공되어 편안한 시간을 보낼 수 있다.",
      images: [
        "코랄라니1.jpeg",
        "코랄라니2.jpeg",
        "코랄라니3.jpeg",
        "코랄라니4.jpeg",
        "코랄라니5.jpeg",
      ],
      sns: "@cafecoralani",
      hash: "#Photo Zone #Cafe",
      contentId: "2832636",
      sigun: "부산 기장군",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%BD%94%EB%9E%84%EB%9D%BC%EB%8B%88/place/1564086471?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "온더버튼",
      text: "무남 해변에 위치한 이 카페는 바다 전망으로 유명하다. 1층은 실내 공간이고 2층은 옥상 공간이며 깔끔하고 아늑한 실내 공간에서 바다 전망을 즐길 수 있다. 카페 건물 옆 바다를 볼 수 있는 공간은 사진 촬영 존으로 활용된다. 카운터부터 내부 공간까지 많은 테이블을 찾을 수 있다. 조용한 시간을 즐기고 싶다면 일찍 방문하는 것을 추천한다.",
      images: [
        "온더버튼1.jpeg",
        "온더버튼2.jpeg",
        "온더버튼3.jpeg",
        "온더버튼4.jpeg",
        "온더버튼5.jpeg",
      ],
      sns: "",
      hash: "#Photo Zone #Cafe",
      contentId: "2839753",
      sigun: "강원 고성군 죽왕면",
      contentType: "39",
      link: "https://map.naver.com/p/search/%EC%98%A8%EB%8D%94%EB%B2%84%ED%8A%BC/place/1567519812?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
  ],
  [
    {
      title: "mrnw",
      text: "mrnw는 누구나 마음속으로 꿈꾸는 이상적인 공간 하지만, 어디에도 존재하지 않는 공간을 현실로 만들고자 하는 생각에서 시작합니다. 자연속에서 mrnw와 함께 전시, 문화, 예술, f&b등 다양한 컨텐츠를 만나실 수 있습니다.",
      images: [
        "mrnw1.jpeg",
        "mrnw2.jpeg",
        "mrnw3.jpeg",
        "mrnw4.jpeg",
        "mrnw5.jpeg",
      ],
      sns: "@miraenongwon",
      hash: "#Culture Complex #Cafe #Exhibition #Museum",
      contentId: "2864490",
      sigun: "대구 북구",
      contentType: "14",
      link: "https://map.naver.com/p/search/mrnw/place/1818837708?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "리움미술관",
      text: "리움미술관은 한국 고유의 미를 담고 있는 전통미술과 생동하는 현대미술, 시대적 가치를 반영한 국제미술이 함께 공존하는 세계를 향한 열린 미술관입니다. 리움은 과거와 현재를 바탕으로 미래를 함께 모색하고, 시대와 장르를 초월한 융합미술관으로 관객과 함께 향유하고 소통하는 문화적 공간이 되고자 합니다.",
      images: [
        "리움미술관1.jpeg",
        "리움미술관2.jpeg",
        "리움미술관3.jpeg",
        "리움미술관4.jpeg",
        "리움미술관5.jpeg",
      ],
      sns: "@leeummuseumofart",
      hash: "#Culture Complex #Cafe #Exhibition #Museum",
      contentId: "130525",
      sigun: "서울 용산구",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%A6%AC%EC%9B%80%EB%AF%B8%EC%88%A0%EA%B4%80/place/11582919?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "코스모40",
      text: "거대한 폐공장을 리모델링하여 탄생한 코스모40은 커피와 베이커리 등의 식음 경험과 전시, 공연, 퍼포먼스, 워크숍, 커뮤니티 이벤트 등을 통해 문화와 예술을 총체적으로 경험하고 일상을 새롭게 감각하는 영감의 공간입니다.",
      images: [
        "코스모1.jpeg",
        "코스모2.jpeg",
        "코스모3.jpeg",
        "코스모4.jpeg",
        "코스모5.jpeg",
      ],
      sns: "@cosmo.40",
      hash: "#Culture Complex #Cafe #Restaurant #Exhibition #Museum",
      contentId: "2780342",
      sigun: "인천 서구",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%BD%94%EC%8A%A4%EB%AA%A840/place/1081020670?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "밀락더마켓",
      text: "밀락더마켓(Millac the Market)은 키친보리에가 부산의 랜드마크 '더베이101', 다대포 '올드트리마켓'에 이어 세번째로 선보이는 워터프론트 복합문화공간입니다. 기존 복합쇼핑 공간과는 차별화된 열린 광장형 체험 공간을 지향하고, 사람과 사람, 아티스트와 관객, 맛있는 음식과 소비자, 로컬과 문화를 연결하는 가교의 역할로 지역 커뮤니티 활성화에 새로운 활력이 될 것입니다.",
      images: [
        "밀락더마켓1.jpeg",
        "밀락더마켓2.jpeg",
        "밀락더마켓3.jpeg",
        "밀락더마켓4.jpeg",
        "밀락더마켓5.jpeg",
      ],
      sns: "@millac_the_market_official",
      hash: "#Culture Complex #Cafe #Restaurant #Exhibition #Museum",
      contentId: "2862152",
      sigun: "부산 수영구",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%B0%80%EB%9D%BD%EB%8D%94%EB%A7%88%EC%BC%93/place/1192293380?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "바우지움조각미술관",
      text: "바우지움조각미술관은 현대 조각의 대중화와 발전에 기여하기 위해 치과의사 안정모 박사와 조각가 김명숙 관장 부부가 2015년에 건립한 조각 전문 사립미술관 입니다. 바우지움은 다양한 전시와 교육 프로그램, 분위기 있는 커피와 작가들의 아트상품을 만날 수 있는 복합문화 공간을 지향합니다. 아름다운 자연과 건축, 예술이 어우러진 바우지움에서 마음이 정화되는 특별한 경험을 하시기 바랍니다.",
      images: [
        "바우지움1.jpeg",
        "바우지움2.jpeg",
        "바우지움3.jpeg",
        "바우지움4.jpeg",
        "바우지움5.jpeg",
      ],
      sns: "@bauzium",
      hash: "#Culture Complex #Cafe #Restaurant #Exhibition #Museum",
      contentId: "2514838",
      sigun: "강원 고성군",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%B0%94%EC%9A%B0%EC%A7%80%EC%9B%80/place/36845206?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "사운즈 한남",
      text: "사운즈는 한적한 바닷가 까지 멀리 떠나지 않아도 우리가 생활하는 도시 안에서 충분한 쉼과 행복감을 얻을 수 있는 어반 리조트입니다. 도심 안에서 가능한 작지만 의미 있는 변화들을 모색하며 도시의 삶에 꼭 필요한 본질에 귀 기울이고, 시간이 지나도 변함 없을 가치들을 고민하여 새로운 도심 라이프스타일을 제안합니다. 한식과 양식을 아우르는 F&B 브랜드들과 관점있는 중형 서점, 갤러리, 플라워숍 등 문화, 라이프스타일에 집중한 리테일 브랜드들이 입점되어 있습니다.",
      images: [
        "사운즈한남1.jpeg",
        "사운즈한남2.jpeg",
        "사운즈한남3.jpeg",
        "사운즈한남4.jpeg",
        "사운즈한남5.jpeg",
      ],
      sns: "@sounds.hannam",
      hash: "#Culture Complex #Cafe #Restaurant #Exhibition #Tourist Destination",
      contentId: "3060939",
      sigun: "서울 용산구",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%82%AC%EC%9A%B4%EC%A6%88%ED%95%9C%EB%82%A8/place/1559396672?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "아유 스페이스",
      text: "낮과 밤이 매우 아름다운 3,500평의 AYU SPACE는 현대적 한국 정원 (아유 가든), 한옥 갤러리 (아유 갤러리), 이탈리안 식당 (아유 재벌 별장), 스페셜티 커피 & 천연 발효 베이커리 공간 (아유 카페)와 북한강 보트 선착장을 갖춘 자연 속 복합 문화 공간입니다. 45여년간 한 재벌가의 여름 별장으로 사용되었던 이 공간은 한국을 대표하는 세계적인 건축가 조병수의 설계와 디자인으로 아유 스페이스로 재탄생 하였습니다. 아유 스페이스는 유럽의 귀족 가문 설립자가 유럽의 어느 곳과 비교하여도 손색이 없는 한국적 문화 휴식 랜드마크를 만들어 전시, 공연, 조경, 건축 예술, 오감 체험 등을 경험할 수 있도록 3년에 걸친 투자와 노력으로 완성한 고품격 복합 문화 공간입니다.",
      images: [
        "아유1.jpeg",
        "아유2.jpeg",
        "아유3.jpeg",
        "아유4.jpeg",
        "아유5.jpeg",
      ],
      sns: "@ayu.space",
      hash: "#Culture Complex #Cafe",
      contentId: "",
      sigun: "경기 남양주시",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%95%84%EC%9C%A0%20%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4/place/1741192061?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "수풍석 뮤지엄",
      text: "수(水)·풍(風)·석(石)뮤지엄은 22만평 드넓은 대지 위에 조성된 주택단지 내에 물·바람·돌을 각각의 테마로 삼고 있는 뮤지엄입니다. 이타미 준이 지향하는 바가 가장 잘 드러난 수풍석 뮤지엄은 미술품이 전시 된 일반적인 곳이 아닌 ‘명상의 공간으로서의 뮤지엄’을 제시하고 있습니다. 자연과 어울어진 이 무릉도원을 함께 느끼고자 2015년 9월부터 비오토피아 주민회에서 개방하여 안내하고 있습니다.",
      images: [
        "수풍석1.jpeg",
        "수풍석2.jpeg",
        "수풍석3.jpeg",
        "수풍석4.jpeg",
        "수풍석5.jpeg",
      ],
      sns: "@sounds.hannam",
      hash: "#Exhibition #Museum",
      contentId: "",
      sigun: "제주 서귀포시",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%88%98%ED%92%8D%EC%84%9D%20%EB%AE%A4%EC%A7%80%EC%97%84/place/37742083?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "의정부 미술 도서관",
      text: `UIJEONGBU의 아트 도서관은 의정부시 밀악동에 위치한 아트 도서관입니다. 의정부 미술 도서관은 사용자들을 위한 실용성을 강조한 디자인으로 구성되어 있습니다.도서관의 주요 키워드는 "연결"입니다. 도서관의 높은 천장과 낮은 책장은 인상적인 가시성을 제공하며 개방감을 극대화한 공간 디자인은 도서관의 매력을 높입니다. 1층은 아트 그라운드로, 주로 건축, 회화, 공예 및 사진과 관련된 책들로 구성되어 있습니다. 2층은 일반 그라운드로, 어린이와 성인이 함께 즐길 수 있는 공간으로 명확한 목적을 가지고 있습니다. 3층의 멀티 그라운드는 체험과 커뮤니티를 위한 공간으로, 카페가 있습니다. 의정부 미술 도서관 아트 도서관에 어울리는 음악은 무음입니다. 공간을 리뷰할 때, 가끔 음악이 없는 것이 공간에 어울리는 음악이라고 말하기도 합니다. 의정부 미술 도서관은 그런 공간 중 하나입니다.`,
      images: [
        "의정부미술도서관1.jpeg",
        "의정부미술도서관2.jpeg",
        "의정부미술도서관3.jpeg",
        "의정부미술도서관4.jpeg",
        "의정부미술도서관5.jpeg",
      ],
      sns: "@artlibrary_ujb",
      hash: "#Culture Complex #Library #Exhibition #Museum",
      contentId: "2705299",
      sigun: "경기 의정부 민락동",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%9D%98%EC%A0%95%EB%B6%80%20%EB%AF%B8%EC%88%A0%20%EB%8F%84%EC%84%9C%EA%B4%80/place/1537794602?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "사유원",
      text: `나를 마주하다, 내안의 숲 사유원 '사유원'은 오랜 풍상을 이겨낸 나무와 마음을 빚은 석상, 아름다운 건축물이 함께하는 고요한 사색의 공간입니다. 단순한 수목원 관람에서 한발 더 나아가 원내를 거닐며 자아를 돌아보고 깊이 생각하게 하는, 진정한 '사유'의 정원입니다.`,
      images: [
        "사유원1.jpeg",
        "사유원2.jpeg",
        "사유원3.jpeg",
        "사유원4.jpeg",
        "사유원5.jpeg",
      ],
      sns: "@sayuwon",
      hash: "#Exhibition #Museum",
      contentId: "2815446",
      sigun: "대구 군위군",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%82%AC%EC%9C%A0%EC%9B%90/place/1491443249?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "청운문학도서관",
      text: `청운문학도서관은 한옥으로 지어진 종로구 16번째 도서관으로 독서와 사색, 휴식이 가능한 매력적인공간입니다. 시, 소설, 수필 위주의 다양한 문학 도서를 소장하고 있으며 주민들에게 각종 독서모임 장소를 제공하는 것은 물론 국내 문학 작품 및 작가 중심의 기획전시와 인문학 강연, 시 창작교실 등을 운영하고 있습니다 `,
      images: [
        "청운문학도서관1.jpeg",
        "청운문학도서관2.jpeg",
        "청운문학도서관3.jpeg",
        "청운문학도서관4.jpeg",
        "청운문학도서관5.jpeg",
      ],
      sns: "https://lib.jongno.go.kr/",
      hash: "#Exhibition #Museum",
      contentId: "2692866",
      sigun: "서울 종로구",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%B2%AD%EC%9A%B4%EB%AC%B8%ED%95%99%EB%8F%84%EC%84%9C%EA%B4%80/place/1861798432?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "양천공원 책쉼터",
      text: `양천공원 책쉼터는 자연과 사람, 책이 한 데 어우러진 커뮤니티 쉼터입니다. 아이들이 책을 읽으면서도 마음껏 뛰어놀 수 있는 공간, 어른들에게는 정신없는 도시생활 중 마음 편히 쉬어갈 수 있는 공간, 도심 속 오아시스 같은 싱그러운 공간을 꿈꾸고 있습니다.`,
      images: [
        "양천공원책쉼터1.jpeg",
        "양천공원책쉼터2.jpeg",
        "양천공원책쉼터3.jpeg",
        "양천공원책쉼터4.jpeg",
        "양천공원책쉼터5.jpeg",
      ],
      sns: "@ycbookshelter23",
      hash: "#Nature #Library",
      contentId: "",
      sigun: "서울 양천구",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%96%91%EC%B2%9C%EA%B3%B5%EC%9B%90%20%EC%B1%85%EC%89%BC%ED%84%B0/place/1768596660?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "송은",
      text: `헤르조그 & 드 뫼롱이 한국에서 진행한 첫 번째 건축물인 송은문화재단 신사옥 '송은'은 도산대로에 위치한 비영리 전시 공간입니다. 청담동 중심부에 위치한 송은 한국 작가들과 더불어 국제 동시대 미술을 조명하는 문화의 중심지가 되고자 합니다.`,
      images: [
        "송은1.jpeg",
        "송은2.jpeg",
        "송은3.jpeg",
        "송은4.jpeg",
        "송은5.jpeg",
      ],
      sns: "@ycbookshelter23",
      hash: "#Nature #Library",
      contentId: "2782156",
      sigun: "서울 강남구",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%86%A1%EC%9D%80/place/13558974?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
  ],
  [
    {
      title: "그래픽",
      text: `서울 용산구에 위치한 그래픽은 건물 외관이 바벨로니아 타워처럼 생겼습니다. 독특한 생김새와 달리 이곳은 그래픽 노블, 만화, 아트북 전문 서점 입니다. 내부 공간은 현대적이며 입장료를 내면 원하는 모든 책을 읽을 수 있습니다. 독특한 장소에서 만화를 볼 수 있는 좋은 경험을 할 수 있습니다.`,
      images: [
        "그래픽1.jpeg",
        "그래픽2.jpeg",
        "그래픽3.jpeg",
        "그래픽4.jpeg",
        "그래픽5.jpeg",
      ],
      sigun: "서울 용산구",
      sns: "@graphic.fan",
      hash: "#Shop #Bookstore",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EA%B7%B8%EB%9E%98%ED%94%BD%5C/place/1867194239?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "LCDC",
      text: `LCDC SEOUL은 저마다의 이야기를 가진 크고 작은 브랜드들이 모여있는 공간플랫폼입니다. 여러 브랜드가 서로 협력하여 만든 각자의 이야기는 하나의 매력적인 이야기가 되어 LCDC SEOUL 속에서 펼쳐집니다. 일상의 조각을 모아주는 따뜻한 카페, 다양한 브랜드를 경험할 수 있는 팝업 공간, 여행과 삶의 이야기를 담은 패션 라이프스타일 큐레이션 샵, 일상의 즐거움을 더해주는 다양한 스몰 브랜드 샵들 그리고, 못다 한 이야기를 나누는 루프탑 바. 이들 모두는 LCDC SEOUL을 이루는 다채로움 속에서 일관성과 통일성이 유지되도록 섬세하게 구성되었습니다. 공간 속의 다양한 이야기는 복합적인 경험 요소들을 통해 깊이 있는 의식과 즐거움, 만족을 줄 것 입니다.`,
      images: [
        "LCDC1.jpeg",
        "LCDC2.jpeg",
        "LCDC3.jpeg",
        "LCDC4.jpeg",
        "LCDC5.jpeg",
      ],
      sigun: "서울 성동구",
      sns: "@lcdc.seoul",
      hash: "#Culture Complex #Shop #Cafe #Restaurant #Exhibition #Museum #Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/LCDC/place/1450511980?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "팬암 성수플래그쉽스토어",
      text: `PAN AM은 과거 항공사 브랜드에서 패션 브랜드로 새롭게 나타난 브랜드입니다. PAN AM 성수동 스토어는 공항 터미널 같은 입구가 있습니다. 이는 과거의 팬암부터 현재의 팬암까지 표한할 수 있도록 하는 건축 미학이 담겨 있습니다.`,
      images: [
        "팬암1.jpeg",
        "팬암2.jpeg",
        "팬암3.jpeg",
        "팬암4.jpeg",
        "팬암5.jpeg",
      ],
      sigun: "서울 성동구",
      sns: "@lcdc.seoul",
      hash: "#Shop",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%8C%AC%EC%95%94/place/1053954003?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "DIOR 성수",
      text: `세계적인 패션 브랜드 디올이 22년 5월 1일 성수동에 오픈했습니다. 프랑스 파리에 위치한 디올 플래그쉽 스토어 30 몽테뉴를 축소한 형태로 건축했으며, 이는 마치 한국 성수동이 아닌 파리 몽테뉴 거리에 있는 느낌을 줍니다. 주변은 화려한 꽃, 우거진 나무 및 푸른 잔디로 가득 차 있어, 동화 같은 프랑스 정원을 경험하는 것처럼 느끼게 합니다. 디올에 관심이 있다면 방문하는 것을 추천드립니다.`,
      images: [
        "디올1.jpeg",
        "디올2.jpeg",
        "디올3.jpeg",
        "디올4.jpeg",
        "디올5.jpeg",
      ],
      sigun: "서울 성동구",
      sns: "",
      hash: "#Shop# Cafe",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/DIOR%20%EC%84%B1%EC%88%98/place/1289759192?c=12.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "콤포트",
      text: `콤포트 서울은 새로운 영감을 위한 컬처 플랫폼입니다. 자체 브랜드와 감도 높은 국내외 브랜드 셀렉션으로 구성된 콤포트 스토어와 전시공간 그라운드 바이 콤포트, 독창적인 커피와 와인을 즐길 수 있는 카페 콤포트, 탁 트인 뷰를 감상할 수 있는 테라스를 만나실 수 있습니다.`,
      images: [
        "콤포트1.jpeg",
        "콤포트2.jpeg",
        "콤포트3.jpeg",
        "콤포트4.jpeg",
        "콤포트5.jpeg",
      ],
      sigun: "서울 용산구",
      sns: "@comfort.seoul",
      hash: "#Culture Complex #Shop #Cafe #Dessert /Bakery",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%BD%A4%ED%8F%AC%ED%8A%B8/place/1540168051?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "아더에러 신사 스페이스",
      text: `브랜드 아더는 시간의 흐름 속에서 각자 떨어져 존재하는 고유시간과 차원이 서로 유기적으로 연결되고 소통하는 세계를 상상했다. 그리고 이 상상을 물질과 빛이라는 메인 테마와 건축, 오브제, 뉴미디어 아트에 접목하여 아더 스페이스 3.0 신사 플래그십 스토어를 구현해냈다. 총 6개 층의 스페셜 섹션들로 구성된 아더 스페이스 3.0에서 다양한 디지털 아티스트와 협업한 뉴미디어 아트와 1층 메인 전시 공간을 만나보세요.`,
      images: [
        "아더에러1.jpeg",
        "아더에러2.jpeg",
        "아더에러3.jpeg",
        "아더에러4.jpeg",
        "아더에러5.jpeg",
      ],
      sigun: "서울 강남구",
      sns: "@ader_error",
      hash: "#Photo Zone #Culture Complex #Shop #Cafe #Exhibition #Museum",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%95%84%EB%8D%94%EC%97%90%EB%9F%AC%20%EC%8B%A0%EC%82%AC%20%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4/place/1728723319?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "북촌 설화수의 집",
      text: `서울에서 가장 잘 알려진 한옥 마을 중 하나인 북촌에는 1930년대의 한옥과 1960년대의 서양식 주택이 결합된 공간이 있습니다. Sulwhasoo를 위한 이 공간은 한옥 스타일의 기둥, 가로보, 지붕을 보존하여 영원한 아름다움과 현대적인 우아함을 함께 느끼게 합니다. 한국 문화의 본격적인 매력과 한옥과 서양 주택 스타일의 조화로운 공존을 경험하고 싶다면 꼭 방문해야 할 곳입니다. 한국적인 가치와 아름다움을 동시대적 해석으로 담아낸 설화수의 집, 전통과 현대의 미감이 공간 곳곳에 펼쳐진 설화수의 집에서 아름다운 여정을 시작해보세요.`,
      images: [
        "설화수1.jpeg",
        "설화수2.jpeg",
        "설화수3.jpeg",
        "설화수4.jpeg",
        "설화수5.jpeg",
      ],
      sigun: "서울 종로구",
      sns: "",
      hash: "#Photo Zone #Culture Complex #Shop #Cafe #Exhibition #Museum",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%B6%81%EC%B4%8C%20%EC%84%A4%ED%99%94%EC%88%98%EC%9D%98%20%EC%A7%91/place/1843846719?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "현대카드 아트 라이브러리",
      text: `현대카드 아트 라이브러리는 아트 입문자부터 전문가까지 책을 통해 누구나 자신만의 속도와 방식으로 컨템포러리 아트를 즐길 수 있는 공간입니다. 종이 책 너머로 아티스트가 건네는 낯선 질문은 반복되는 일상에서 벗어나 새로운 관점과 아이디어를 찾는 계기가 되기에 충분합니다. 좋은 예술적 취향과 안목을 지닌 친구의 서재나 동네 서점처럼 언제든 무심코 들려 편안히 머물 수 있는 공간, 방문을 추천드립니다.`,
      images: [
        "현대카드1.jpeg",
        "현대카드2.jpeg",
        "현대카드3.jpeg",
        "현대카드4.jpeg",
        "현대카드5.jpeg",
      ],
      sigun: "서울 용산구",
      sns: "https://dive.hyundaicard.com",
      hash: "#Culture Complex #Music",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%98%84%EB%8C%80%EC%B9%B4%EB%93%9C%20%EC%95%84%ED%8A%B8%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/place/1901341248?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "템버린즈 성수 플래그십스토어",
      text: `템버린즈는 감각적 아트와 아름다움을 지향하는 코스메틱 브랜드입니다. 성수동의 플래그십스토어는 외관이 독특하다. 노출 콘크리트 기둥 사이에 유리를 배치하여 지나가는 사람들도 하여금 호기심을 불러 일으킵니다. 실내는 좋은 향으로 가득차 있어, 천장 유리너머로 보이는 콘크리트 기둥과 대비되는 느낌을 주어 묘한 감정을 느끼게 합니다.`,
      images: [
        "템버린즈1.jpeg",
        "템버린즈2.jpeg",
        "템버린즈3.jpeg",
        "템버린즈4.jpeg",
        "템버린즈5.jpeg",
      ],
      sigun: "서울 성동구",
      sns: "@tamburinsofficial",
      hash: "#Culture Complex #Music",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%85%9C%EB%B2%84%EB%A6%B0%EC%A6%88%20%EC%84%B1%EC%88%98%20%ED%94%8C%EB%9E%98%EA%B7%B8%EC%8B%AD%EC%8A%A4%ED%86%A0%EC%96%B4/place/1539672429?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "무신사 스탠다드 홍대",
      text: `무신사 스탠다드의 첫 번째 플래그십 스토어, 현대적이면서 실용적인 건축 디자인 돋보이는 장소입니다. 이러한 건축 디자인은 다른 SPA 브랜드와 차이를 두는 시각적 효과를 경험할 수 있습니다. 무신사 옷을 사거나 홍대에 방문할 일이 있다면 무신사 스탠다드 스토어를 가보시는 것을 추천합니다.`,
      images: [
        "무신사1.jpeg",
        "무신사2.jpeg",
        "무신사3.jpeg",
        "무신사4.jpeg",
        "무신사5.jpeg",
      ],
      sigun: "서울 마포구",
      sns: "",
      hash: "#Culture Complex #Music",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%AC%B4%EC%8B%A0%EC%82%AC%20%EC%8A%A4%ED%83%A0%EB%8B%A4%EB%93%9C%20%ED%99%8D%EB%8C%80/place/1130856933?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "1유로프로젝트 코끼리빌라",
      text: `서울 도심 성수동 인근 연면적 165평 4층 빈집을 3년간 무상으로 빌려 리모델링 후 2023년 2월에 문을 열었습니다. 다양한 브랜드와 함께하고 있으며 좋은 라이프스타일을 제안하고 있습니다. 1유로 프로젝트의 취지와 방향은 더 나은 라이프스타일을 공유하는 플랫폼입니다. 의미있는 가치셀링을 지항하며, 서로 더불어 사는 삶의 태도와 방식을 나눕니다. 사람과 사람을, 사람과 브랜드를, 동네와 도시를 서로 연결하며 좋은 커뮤니티를 형성하고자 합니다. 시작하거나 성장하고 있는 브랜드들이 만나 좋은 도시를 꿈꾸는 '1유로프로젝트', 우리 모두가 좋은 라이프스타일 판매자이자 소비자입니다. 모두가 상생할 수 있도록 도시 상생기획 1유로 프로젝트 그 첫번째 시작, 코끼리 빌라입니다.`,
      images: [
        "코끼리빌라1.jpeg",
        "코끼리빌라2.jpeg",
        "코끼리빌라3.jpeg",
        "코끼리빌라4.jpeg",
        "코끼리빌라5.jpeg",
      ],
      sigun: "서울 성동구",
      sns: "@1_euro_projects",
      hash: "#Shopping Mall #Photo Zone #Culture Complex #Cafe #Restaurant #Dessert/Bakery #Tourist Destination",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/1%EC%9C%A0%EB%A1%9C%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%20%EC%BD%94%EB%81%BC%EB%A6%AC%EB%B9%8C%EB%9D%BC/place/1621825485?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
  ],
  [
    {
      title: "황인용뮤직스페이스카메라타",
      text: `카메라타뮤직스페이스는 1970년대부터 약40여년간 라디오 디제이로 활약한 방송인 황인용이 수집한 1920년대 빈티지 오디오와 LP/CD 컬렉션을 기반으로 만들어진 클래식음악감상실입니다. 건축가 조병수의 설계로 지어진 건축물로 잘 알려져 있으며, 육중한 콘크리트박스의 좁은 철문을 열고 들어가면 10미터의 높은 공간을 가득 채우는 아날로그 사운드를경험할 수 있습니다. 조용하고 차분한 분위기 속에서 책을 읽고 음악을 듣는 장소입니다.`,
      images: [
        "뮤직스페이스1.jpeg",
        "뮤직스페이스2.jpeg",
        "뮤직스페이스3.jpeg",
        "뮤직스페이스4.jpeg",
        "뮤직스페이스5.jpeg",
      ],
      sigun: "경기 파주시",
      sns: "@musicspacecamerata",
      hash: "#Cafe",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%99%A9%EC%9D%B8%EC%9A%A9%EB%AE%A4%EC%A7%81%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4%EC%B9%B4%EB%A9%94%EB%9D%BC%ED%83%80/place/11681355?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "뮤직컴플렉스서울",
      text: `인사동에 뜬 붉은노을, 뮤직컴플렉스서울은 아날로그 감성과 힙한 감성이 공존하는 장소입니다. 이곳은 국내 최대 규모의 LP 카페로 각 자리마다 개별 턴테이블과 헤드셋이 구비되어있으며, 2만여장의 LP 속에서 여러분이 좋아하는 음악을 직접 디깅하여 자유롭게 청음하실 수 있는 공간입니다. 음악을 좋아하신다면 추천드립니다.`,
      images: [
        "뮤직컴플렉스1.jpeg",
        "뮤직컴플렉스2.jpeg",
        "뮤직컴플렉스3.jpeg",
        "뮤직컴플렉스4.jpeg",
        "뮤직컴플렉스5.jpeg",
      ],
      sigun: "서울 종로구",
      sns: "@music.complex.seoul",
      hash: "#Culture Complex #Cafe #Music",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%AE%A4%EC%A7%81%EC%BB%B4%ED%94%8C%EB%A0%89%EC%8A%A4%EC%84%9C%EC%9A%B8/place/1063364661?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "평균율",
      text: `평균율은 을지로에 위치한 BAR 입니다. 이곳에서 아름다운 Jazz, Samba, Bossanova, Blues, Fusion Soul Funk등과 같이 다양한 장르의 음악을 감상하실 수 있습니다. 또한 와인과 잘 어울리는 여러 메뉴들이 존재하니 연인과 로맨틱한 시간을 보낼 수 있습니다.`,
      images: [
        "평균율1.jpeg",
        "평균율2.jpeg",
        "평균율3.jpeg",
        "평균율4.jpeg",
        "평균율5.jpeg",
      ],
      sigun: "서울 중구",
      sns: "@pky_seoul",
      hash: "#Shop #Cafe #Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%8F%89%EA%B7%A0%EC%9C%A8/place/1283997031?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "내도음악상가",
      text: `제주시에 위치한 내도음악상가는 제주도의 아름다운 바다와 함께 술을 마실 수 있는 공간입니다. 특히 해 질 녁 바다에 비치는 노을과 분위기 있는 음악이 술의 맛을 올려줍니다.`,
      images: [
        "내도음악상가1.jpeg",
        "내도음악상가2.jpeg",
        "내도음악상가3.jpeg",
        "내도음악상가4.jpeg",
        "내도음악상가5.jpeg",
      ],
      sigun: "제주 제주시",
      sns: "@recordbar.naedo",
      hash: "#Music #Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%82%B4%EB%8F%84%EC%9D%8C%EC%95%85%EC%83%81%EA%B0%80/place/1200733900?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "현대카드 뮤직 라이브러리",
      text: `이태원로를 따라 가다보면 독특한 구조의 건물을 보실 수 있습니다. 건물 외벽은 현대카드의 아트 정신이 느껴지는 그림이 그려져 있습니다. 1층은 카페이며, 2층에는 희귀한 바이닐 레코드와 턴테이블이 있습니다. 계단을 올라가서 3층을 방문하여 다양한 시대와 국가의 음반을 감상할 수 있습니다. 희귀한 바이닐 레코드와 중요한 자료를 보유하고 있으므로 현대카드 소지자만 출입할 수 있습니다.`,
      images: [
        "현대카드뮤직라이브러리1.jpeg",
        "현대카드뮤직라이브러리2.jpeg",
        "현대카드뮤직라이브러리3.jpeg",
        "현대카드뮤직라이브러리4.jpeg",
        "현대카드뮤직라이브러리5.jpeg",
      ],
      sigun: "서울 용산구",
      sns: "https://dive.hyundaicard.com/web/musiclibrary/spaceMain.hdc",
      hash: "#Culture Complex",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%98%84%EB%8C%80%EC%B9%B4%EB%93%9C%20%EB%AE%A4%EC%A7%81%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/place/36665677?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "힐즈 앤 유로파",
      text: `용산구 서울 용산동에 위치한 수십 개의 펍으로 가득한 거리에 있는 HILLS & EUROPA는 카페와 바입니다. HILLS & EUROPA는 독특한 분위기를 자랑합니다. LP 음반을 들으며 시간을 보내기에 좋은 장소입니다. 낮에는 커피 바로 운영되며 저녁에는 술 한 잔을 즐기기에 좋은 장소입니다`,
      images: [
        "힐즈앤유로파1.jpeg",
        "힐즈앤유로파2.jpeg",
        "힐즈앤유로파3.jpeg",
        "힐즈앤유로파4.jpeg",
        "힐즈앤유로파5.jpeg",
      ],
      sigun: "서울 용산구",
      sns: "@hillsandeuropa",
      hash: "#Cafe #Restaurant #Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%9E%90%EC%A6%88%20%EC%95%A4%20%EC%9C%A0%EB%A1%9C%ED%8C%8C/place/1995360729?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "로스트 앤 파운드",
      text: `다양한 피규어와 그림들이 돋보이는 BAR입니다. 로스트 앤 파운드는 저녁 6시 부터는 Eat Your Crust 로 피자를 만들고 8시 30분 부터는 Bourbon Whiskey Bar 를 운영중이며 주말 낮에는 the Breakfast Club 으로 브런치를 준비합니다.`,
      images: [
        "로스트앤파운드1.jpeg",
        "로스트앤파운드2.jpeg",
        "로스트앤파운드3.jpeg",
        "로스트앤파운드4.jpeg",
        "로스트앤파운드5.jpeg",
      ],
      sigun: "서울 중구",
      sns: "@lostandfound_bourbonbar",
      hash: "#Cafe #Restaurant #Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%A1%9C%EC%8A%A4%ED%8A%B8%20%EC%95%A4%20%ED%8C%8C%EC%9A%B4%EB%93%9C/place/1393425421?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "콩치노콘크리트",
      text: `콩치노(concino)는 라틴어로 '공명'을 뜻합니다. 콩치노에서 유추할 수 있듯이 콩치노 콘코르티는 음악을 감상할 수 있는 공간입니다. 멋진 콘크리트 디자인과 안에서 나오는 음악은 아름다운 공명을 일으킵니다. 또한 가운데 콘서트홀이 있어 운이 좋다면 공연을 감상하실 수 있습니다.`,
      images: [
        "콩치노콘크리트1.jpeg",
        "콩치노콘크리트2.jpeg",
        "콩치노콘크리트3.jpeg",
        "콩치노콘크리트4.jpeg",
        "콩치노콘크리트5.jpeg",
      ],
      sigun: "경기 파주시",
      sns: "@lostandfound_bourbonbar",
      hash: "#Music #Exhibition #Museum",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%BD%A9%EC%B9%98%EB%85%B8/place/1209333754?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
  ],
  [
    {
      title: "바 스왈로",
      text: `바 스왈로는 서울 지하철 6호선 한남역과 이태원역 사이에 위치한 한남동에 있습니다. 바텐더 김진환씨는 2018년 월드 클래스 바텐더 대회에서 우승한 후 한남 커피 바 K, 바 머스크, 롯데호텔의 드로잉 룸 바 등 다른 유명한 바에서 근무한 뒤 이 바를 열었습니다. 간판이 없고, 1층 초록색 문이 정문입니다. `,
      images: [
        "바스왈로1.jpeg",
        "바스왈로2.jpeg",
        "바스왈로3.jpeg",
        "바스왈로4.jpeg",
        "바스왈로5.jpeg",
      ],
      sigun: "서울 용산구",
      sns: "@bar.swallow",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%B0%94%20%EC%8A%A4%EC%99%88%EB%A1%9C/place/1843082518?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "BAR CHAM",
      text: `바 참(BAR CHAM)은 서촌 골목에 위치한 한옥으로 된 Bar입니다. 바참의 창업 멤버인 임병진씨는 2015년 월드 클래스 바텐더 대회에서 우승한 바텐더 입니다. 바참은 기존에 있던 한옥의 잔기둥을 없앤 후 철근 프레임을 두르지 않은 채 6m에 이르는 대들보 세 개를 건너질러 지붕을 떠받쳤고, 거대한 대들보가 가로지르는 가운데 한쪽 벽면에 술이 빼곡하며, 참나무로 만든 바가 지붕과 나란히 뻗어 있습니다. 소재를 참나무로 통일하는 한편 공간을 직선으로 시원하게 구성한 덕에 20평이 채 되지 않는 공간임에도 전혀 좁게 느껴지지 않습니다. 바참은 한국의 전통주를 기주로 한 칵테일을 판매하고 있습니다.`,
      images: [
        "CHAM1.jpeg",
        "CHAM2.jpeg",
        "CHAM3.jpeg",
        "CHAM4.jpeg",
        "CHAM5.jpeg",
      ],
      sigun: "서울 종로구",
      sns: "@bar.cham",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/BAR%20CHAM/place/1245369400?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "숙희",
      text: `숙희는 일본 긴자 출신 이수원 오너바텐더의 클래식 위스키를 판매하는 바입니다. 허름한 문을 열면 화려한 자개장식과 높은 층고 덕분에 독특한 인상을 줍니다. 분위기 좋은 곳에서 위스키, 칵테일을 즐기고 싶다면 이곳을 추천합니다.`,
      images: [
        "숙희1.jpeg",
        "숙희2.jpeg",
        "숙희3.jpeg",
        "숙희4.jpeg",
        "숙희5.jpeg",
      ],
      sigun: "서울 중구",
      sns: "@soowonopa_sookhee",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%88%99%ED%9D%AC/place/1903221041?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "르챔버",
      text: `책장으로 된 문이 인상적인 Bar 르챔버 입니다. 이 문을 지나면 고급스러운 Bar 분위기가 묻어나는 인테리어가 돋 보입니다. 편안하게 술을 마시고 싶다면 르챔버 추천 드립니다.`,
      images: [
        "르챔버1.jpeg",
        "르챔버2.jpeg",
        "르챔버3.jpeg",
        "르챔버4.jpeg",
        "르챔버5.jpeg",
      ],
      sigun: "서울 강남구",
      sns: "@le_chamber",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%A5%B4%EC%B1%94%EB%B2%84/place/35507086?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "베스퍼",
      text: `"집 근처에 이런 가게가 있으면 좋겠다."라는 마음으로 만든 Bar 입니다. 클래식 바텐딩으로 세계적으로 유명한 일본 바텐더의 수제자로 쌓은 탄탄한 기본기를 바탕으로, 손님의 입맛과 그 날의 기분에 맞춘 최적의 한잔을 내는 데에 최선을 다하는 Bar 입니다. 인테리어는 클래식하며 기본에 충실한 컨셉이 느껴집니다.`,
      images: [
        "베스퍼1.jpeg",
        "베스퍼2.jpeg",
        "베스퍼3.jpeg",
        "베스퍼4.jpeg",
        "베스퍼5.jpeg",
      ],
      sigun: "서울 서초구",
      sns: "@vesper_seoul",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%B2%A0%EC%8A%A4%ED%8D%BC/place/1001563664?c=15.00,0,0,0,dh&placePath=%3Fentry%253Dbmp",
    },
    {
      title: "마하 한남",
      text: `일반적인 Bar 컨셉의 인테리어가 아닌 따뜻한 카페와 같은 디자인을 갖추었습니다. 이는 마하 한남의 사장님의 건축 정신이 깃든 디자인이라 볼 수 있습니다. 한적한 마을 속 기와 장식을 가진 폐업한 목욕탕 건물, 한강이 펼쳐지는 테라스와 큰 창이 있는 40평 남짓 한 공간입니다. 사무실과 건축서재, 누구든 와서 쉴 수 있는 카페가 공존하는 공간을 완성했습니다. 이 곳에서 좋은 사람들과 즐거운 일들을 도모하는 공간입니다.`,
      images: [
        "마하한남1.jpeg",
        "마하한남2.jpeg",
        "마하한남3.jpeg",
        "마하한남4.jpeg",
        "마하한남5.jpeg",
      ],
      sigun: "서울 용산구",
      sns: "@maha.hannam",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EB%A7%88%ED%95%98%20%ED%95%9C%EB%82%A8/place/1584365222?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "포시즌스 호텔 서울 찰스 H.",
      text: `전설적인 미국 작가인 찰스 H. 베이커의 이름을 딴 찰스 H. 바는 이국적이고 화려한 매력이 가득한 공간으로, 칵테일 애호가들에게 완벽한 메뉴를 제공하며 지하의 비밀 통로를 통해 연결됩니다.`,
      images: [
        "찰스H1.jpeg",
        "찰스H2.jpeg",
        "찰스H3.jpeg",
        "찰스H4.jpeg",
        "찰스H5.jpeg",
      ],
      sigun: "서울 종로구",
      sns: "@charleshseoul",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%ED%8F%AC%EC%8B%9C%EC%A6%8C%EC%8A%A4%20%ED%98%B8%ED%85%94%20%EC%84%9C%EC%9A%B8%20%EC%B0%B0%EC%8A%A4%20H./place/37402393?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
    {
      title: "코블러 연희",
      text: `연희동의 한 개인 주택이 코블러 연희로 변모했습니다. 코블러 연희는 다양한 시그니처 칵테일, 위스키 등 각종 주류를 판매하고 있습니다. 고객 맞춤형 서비스를 선보이며 만족스러운 시간을 제공하고 합니다. 서늘한 날씨에는 실외에서의 음료 한 잔이 로맨틱한 분위기를 낼 수 있는 곳입니다.`,
      images: [
        "코블러연희1.jpeg",
        "코블러연희2.jpeg",
        "코블러연희3.jpeg",
        "코블러연희4.jpeg",
        "코블러연희5.jpeg",
      ],
      sigun: "서울 서대문구",
      sns: "@cobbler_yeonhee",
      hash: "#Bar",
      contentId: "",
      contentType: "14",
      link: "https://map.naver.com/p/search/%EC%BD%94%EB%B8%94%EB%9F%AC%20%EC%97%B0%ED%9D%AC/place/1578448821?c=15.00,0,0,0,dh&isCorrectAnswer=true",
    },
  ],
];
